### ISSUE TITLE
Discussion: Error: INTERNAL: Panic! This is a bug!

### ISSUE THREAD

**Issue by shaiktas** [milvus-io/milvus-sdk-java#1097]
Hello When i am trying to connect Milvus with Certs from flink environment. i am getting error as `Failed to initialize connection. Error: INTERNAL: Panic! This is a bug!` Below is full stack trace:

Flink Version: 1.19.1
Java/JDK : 11
milvus sdk (io.milvus:milvus-sdk-java:2.4.4) : 2.4.4/2.3.5
Do we have any specific dependencies version mapping between flink->Milvus SDK? 

---

	at com.apple.isds.milvus.sink.MilvusRowDataSinkConnector.open(MilvusRowDataSinkConnector.java:44) ~[?:?]
	at org.apache.flink.api.common.functions.RichFunction.open(RichFunction.java:119) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:46) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:107) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreStateAndGates(StreamTask.java:799) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$restoreInternal$3(StreamTask.java:753) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.call(StreamTaskActionExecutor.java:100) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:753) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:712) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:751) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566) ~[flink-dist-1.19.1.jar:1.19.1]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.RuntimeException: Failed to initialize connection. Error: INTERNAL: Panic! This is a bug!

--

**Comment by yhmo** [comment]
"INTERNAL: Panic! This is a bug!" is an error thrown from gRPC lib. There might be dependencies confliction in your project.
Use "mvn dependency:tree -Dverbose" to print the dependency tree.

**Comment by yhmo** [comment]
Answered. INTERNAL: Panic! is a gRPC-level error usually caused by dependency conflicts; use mvn dependency:tree to inspect. Closing.
