### ISSUE TITLE
Fail to run the example program

### ISSUE THREAD

**Issue by yt7589** [milvus-io/milvus-sdk-java#151]
When I run this code MgqEngine(Line 15):
Ln 14       ConnectParam connectParam = new ConnectParam.Builder().withHost("192.168.2.15").withPort(19530).build();
Ln15        MilvusClient client = new MilvusGrpcClient(connectParam);

It does not work:
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V
	at io.grpc.Metadata$Key.validateName(Metadata.java:742)
	at io.grpc.Metadata$Key.<init>(Metadata.java:750)
	at io.grpc.Metadata$Key.<init>(Metadata.java:668)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:959)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:954)
	at io.grpc.Metadata$Key.of(Metadata.java:705)
	at io.grpc.Metadata$Key.of(Metadata.java:701)
	at io.grpc.internal.GrpcUtil.<clinit>(GrpcUtil.java:80)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.<clinit>(AbstractManagedChannelImplBuilder.java:90)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForTarget(NettyChannelProvider.java:42)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForTarget(NettyChannelProvider.java:23)
	at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:76)
	at io.milvus.client.MilvusGrpcClient.<init>(MilvusGrpcClient.java:68)
	at com.zhuanjingkj.stpbe.mgqs.mgq.MgqEngine.demo(MgqEngine.java:15)
	at com.zhuanjingkj.stpbe.mgqs.SrMgqsApplication.main(SrMgqsApplication.java:20)

My pom.xml file:

<dependency>
            <groupId>io.milvus</groupId>
            <artifactId>milvus-sdk-java</artifactId>
            <version>0.9.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-slf4j-impl</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

How to solve this problem?

**Comment by sahuang** [comment]
You might want to check [this webpage](https://stackoverflow.com/questions/45247193/nosuchmethoderror-com-google-common-base-preconditions-checkargumentzljava-lan).

`java.lang.NoSuchMethodError` happens when there is a version mismatch.
