### ISSUE TITLE
连接调用milvus报错

### ISSUE THREAD

**Issue by sixgodleaf** [milvus-io/milvus-sdk-java#269]
三月 22, 2022 7:09:00 下午 io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
严重: *~*~*~ Channel ManagedChannelImpl{logId=5, target=shuyuan-dev2:19530} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:615)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:261)
	at io.milvus.client.MilvusServiceClient.<init>(MilvusServiceClient.java:43)

**Comment by yhmo** [comment]
Seems the rpc channel is not closed. Call the close() method of the MilvusClient to avoid this error.
