### ISSUE TITLE
status -3 io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service milvus.proto.milvus.MilvusService

### ISSUE THREAD

**Issue by prety16** [milvus-io/milvus-sdk-java#363]
final MilvusServiceClient milvusClient = new MilvusServiceClient(
                ConnectParam.newBuilder()
                        .withHost("***.***.***.***")
                        .withPort(19531)
                        .build());
boolean exist = milvusClient.hasCollection(
                HasCollectionParam.newBuilder().withCollectionName(tableName).build()
        ).getData();

when i execute this code,the response have a exception : status -3 io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service milvus.proto.milvus.MilvusService

SDK versions these two sdk version i had tried ,both   response     have these exception

  <dependency>
            <groupId>io.milvus</groupId>
            <artifactId>milvus-sdk-java</artifactId>
            <version>2.0.4</version>
        </dependency>

  <dependency>
            <groupId>io.milvus</groupId>
            <artifactId>milvus-sdk-java</artifactId>
            <version>2.0.2</version>
        </dependency>
milvus version 2.0.2

**Comment by abratnap** [comment]
I get this on linux with version 2.2.0. This happens in linux and works well in Mac.

```
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method GetLoadingProgress for service milvus.proto.milvus.MilvusService"
	debug_error_string = "{"created":"@","description":"Error received from peer ipv4:*****:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"unknown method GetLoadingProgress for service milvus.proto.milvus.MilvusService","grpc_status":12}"
```

**Comment by zinzinhust96** [comment]
@abratnap please check if there is a mismatch between Milvus and Milvus SDK version. This also happens to me with Milvus and PyMilvus in Python, as specified in https://github.com/milvus-io/pymilvus

**Comment by xiaofan-luan** [comment]
Check the release note here https://milvus.io/docs/release_notes.md.
It's better to match Milvus version and SDK version in each release.

**Comment by stringk245** [comment]
> 2.2.

Did you solve this problem(unknown method GetLoadingProgress for service)? What solved it?

**Comment by xiaofan-luan** [comment]
@yhmo
could you help on that?
Might be work for java SDK?

**Comment by Pravesh22** [comment]
I think this error is raised from CheckHealth interface. This CheckHealth interface was added lately in milvus which might not be available in old version of Milvus. So i think upgrading Milvus to latest version will solve this issue

**Comment by SumeetSinha18** [comment]
Facing the same issue when I load the data into collection using collection.load()
pymilvus-2.2.1
milvus-cli-0.3.2

I have tried upgrading and downgrading  them but any other combination results in compatiblity issue
I am able to create the collection but unable to load data into it.
collection.insert(df) shows success but collection.is_empty results in True.


Error:

pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method GetLoadingProgress for service milvus.proto.milvus.MilvusService"
	debug_error_string = "{"created":"@1687865173.588569389","description":"Error received from peer ipv4:127.0.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"unknown method GetLoadingProgress for service milvus.proto.milvus.MilvusService","grpc_status":12}"

**Comment by yhmo** [comment]
> Facing the same issue when I load the data into collection using collection.load() pymilvus-2.2.1 milvus-cli-0.3.2
> 
> I have tried upgrading and downgrading them but any other combination results in compatiblity issue I am able to create the collection but unable to load data into it. collection.insert(df) shows success but collection.is_empty results in True.
> 
> Error:
> 
> pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with: status = StatusCode.UNIMPLEMENTED details = "unknown method GetLoadingProgress for service milvus.proto.milvus.MilvusService" debug_error_string = "{"created":"@1687865173.588569389","description":"Error received from peer ipv4:127.0.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"unknown method GetLoadingProgress for service milvus.proto.milvus.MilvusService","grpc_status":12}"

The GetLoadingProgress API is available from Milvus v2.2.1. You will get this error if you are using Milvus 2.1.x.

**Comment by fgyang** [comment]
bug content bellow:
Exception in thread "main" io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service milvus.proto.milvus.MilvusService
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
	at io.milvus.grpc.MilvusServiceGrpc$MilvusServiceBlockingStub.connect(MilvusServiceGrpc.java:4777)
	at io.milvus.v2.client.MilvusClientV2.connect(MilvusClientV2.java:155)
	at io.milvus.v2.client.MilvusClientV2.connect(MilvusClientV2.java:109)
	at io.milvus.v2.client.MilvusClientV2.<init>(MilvusClientV2.java:88)
	at xin.zhulin.Test.main(Test.java:22)

milvus version: 2.4.14 
java sdk version: 2.4.7

**Comment by yhmo** [comment]
Not a SDK bug. UNIMPLEMENTED: unknown service milvus.proto.milvus.MilvusService is caused by a version mismatch between the client and the Milvus server. Use a matching SDK/server release. See https://milvus.io/docs/release_notes.md
