### ISSUE TITLE
GeneralExample.java took too much time to build index and error occured when example.describeIndex() was called

### ISSUE THREAD

**Issue by gobigrassland** [milvus-io/milvus-sdk-java#379]
(1) I set row_count = 100 , there were 10000 rows totaly.  The log as follow:
```
========== hasCollection() ==========
2022-09-19 18:49:50 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: HasCollectionParam{collectionName='TEST'}
R{status=0, data=false}
========== createCollection() ==========
2022-09-19 18:49:51 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: CreateCollectionParam{collectionName='TEST', shardsNum=2, description='customer info', fields=[FieldType{name='userID', type='Int64', primaryKey=true, autoID=true, params={}}, FieldType{name='userFace', type='FloatVector', primaryKey=false, autoID=false, params={dim=64}}, FieldType{name='userAge', type='Int8', primaryKey=false, autoID=false, params={}}]}
R{status=0, data=RpcStatus{msg='Success'}}
========== hasCollection() ==========
2022-09-19 18:49:51 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: HasCollectionParam{collectionName='TEST'}
R{status=0, data=true}
========== describeCollection() ==========
2022-09-19 18:49:51 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: DescribeCollectionParam{collectionName='TEST'}
Collection Description{name:'TEST', description:'customer info', id:436098719071600641, shardNumber:2, createdUtcTimestamp:1663584591185, aliases:[], fields:[FieldType{name='userID', type='Int64', primaryKey=true, autoID=true, params={}}, FieldType{name='userFace', type='FloatVector', primaryKey=false, autoID=false, params={dim=64}}, FieldType{name='userAge', type='Int8', primaryKey=false, autoID=false, params={}}]}
========== showCollections() ==========
2022-09-19 18:49:51 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: ShowCollectionsParam{collectionNames='[]', showType=All}
R{status=0, data=status {
}
collection_names: "TEST"
collection_ids: 436098719071600641
created_timestamps: 436098719071600644
created_utc_timestamps: 1663584591185
}
========== loadCollection() ==========
2022-09-19 18:49:51 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: LoadCollectionParam{collectionName='TEST', syncLoad=true, syncLoadWaitingInterval=500, syncLoadWaitingTimeout=60}
R{status=0, data=RpcStatus{msg='Success'}}
========== createPartition() ==========
2022-09-19 18:49:51 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: CreatePartitionParam{collectionName='TEST', partitionName='p1'}
R{status=0, data=RpcStatus{msg='Success'}}
========== hasPartition() ==========
2022-09-19 18:49:51 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: HasPartitionParam{collectionName='TEST', partitionName='p1'}
R{status=0, data=true}
========== showPartitions() ==========
2022-09-19 18:49:51 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: ShowPartitionsParam{collectionName='TEST', partitionNames='[]', showType=All}
R{status=0, data=status {
}
partition_names: "_default"
partition_names: "p1"
partitionIDs: 436098719071600642
partitionIDs: 436098719255101441
created_timestamps: 436098719071600644
created_timestamps: 436098719255101443
created_utc_timestamps: 1663584591185
created_utc_timestamps: 1663584591885
}


2022-09-19 18:49:54 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: InsertParam{collectionName='TEST', partitionName='p1', row_count=100, fields=[Field{fieldName='userAge', row_count=100}, Field{fieldName='userFace', row_count=100}]}
2022-09-19 18:49:54 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: DescribeCollectionParam{collectionName='TEST'}
========== getCollectionStatistics() ==========
2022-09-19 18:49:54 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: GetCollectionStatisticsParam{collectionName='TEST' flush=true}
2022-09-19 18:49:54 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: FlushParam{collectionNames='[TEST]', syncFlush=true, syncFlushWaitingInterval=500, syncFlushWaitingTimeout=60}
Collection row count: 10000
Search without index
========== searchFace() ==========
2022-09-19 18:49:57 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: SearchParam{collectionName='TEST', partitionNames='[]', metricType=L2, target vectors count=5, vectorFieldName='userFace', topK=5, expr='userAge > 50', params='{"nprobe":10}'}
Search time cost: 28ms
Search result of No.0
[(ID: 436097703434181485 Score: 5.766734), (ID: 436097703434181370 Score: 6.0443335), (ID: 436097703434183661 Score: 6.3910513), (ID: 436097703434179358 Score: 6.683622), (ID: 436097703434186921 Score: 6.7253046)]
Output field data for No.0
[82, 55, 95, 80, 92]
Search result of No.1
[(ID: 436097703434182082 Score: 6.422768), (ID: 436097703434188703 Score: 6.86335), (ID: 436097703434186389 Score: 6.88204), (ID: 436097703434187005 Score: 6.9441457), (ID: 436097703434186218 Score: 7.0367785)]
Output field data for No.1
[82, 53, 87, 64, 86]
Search result of No.2
[(ID: 436097703434188018 Score: 6.7716494), (ID: 436097703434180826 Score: 6.776958), (ID: 436097703434182533 Score: 7.495006), (ID: 436097703434182039 Score: 7.5221367), (ID: 436097703434182185 Score: 7.5411596)]
Output field data for No.2
[92, 91, 77, 60, 94]
Search result of No.3
[(ID: 436097703434182214 Score: 6.4064937), (ID: 436097703434181972 Score: 6.4225817), (ID: 436097703434187730 Score: 6.4393225), (ID: 436097703434189320 Score: 6.5812197), (ID: 436097703434184140 Score: 6.802354)]
Output field data for No.3
[77, 93, 56, 85, 59]
Search result of No.4
[(ID: 436097703434188163 Score: 6.28776), (ID: 436097703434181374 Score: 6.39774), (ID: 436097703434182633 Score: 6.404768), (ID: 436097703434183205 Score: 6.4412403), (ID: 436097703434186329 Score: 6.6586475)]
Output field data for No.4
[78, 68, 73, 84, 72]
========== createIndex() ==========
2022-09-19 18:49:57 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: CreateIndexParam{collectionName='TEST', fieldName='userFace', indexName='userFaceIndex', params='{metric_type=L2, params={"nlist":128}, index_type=IVF_FLAT}', syncMode=true, syncWaitingInterval=500, syncWaitingTimeout=600}
2022-09-19 18:59:57 io.milvus.client.AbstractMilvusGrpcClient logWarning 
WARN: Waiting index thread is timeout, index process may not be finished
R{status=0, data=RpcStatus{msg='Success'}}
========== describeIndex() ==========
2022-09-19 18:59:57 io.milvus.client.AbstractMilvusGrpcClient logInfo 
INFO: DescribeIndexParam{collectionName='TEST', indexName='userFaceIndex'}
2022-09-19 18:59:57 io.milvus.client.AbstractMilvusGrpcClient logError 
ERROR: DescribeIndexRequest failed:
index not exist
Exception in thread "main" java.lang.RuntimeException: index not exist
	at io.milvus.GeneralExample.handleResponseStatus(GeneralExample.java:71)
	at io.milvus.GeneralExample.describeIndex(GeneralExample.java:279)
	at io.milvus.GeneralExample.main(GeneralExample.java:508)

Process finished with exit code 1

```

(2) I run  https://github.com/milvus-io/pymilvus/blob/master/examples/example.py with the same number of data. It took only about 4 ms
```
Create connection...

List connections:
[('default', <pymilvus.client.grpc_handler.GrpcHandler object at 0x7f38ac17ed60>)]

collection created: demo

list collections:
['TEST', 'demo']

The number of entity:
10000

Created index:
{'index_type': 'IVF_FLAT', 'params': {'nlist': 1024}, 'metric_type': 'L2'}
time usage:  3.5774714946746826

Search result for 0th vector: 
Top 0: (distance: 14.717127799987793, id: 5894)
Top 1: (distance: 15.107439994812012, id: 4459)
Top 2: (distance: 15.26661491394043, id: 9932)

Search result for 1th vector: 
Top 0: (distance: 0.0, id: 1)
Top 1: (distance: 13.991562843322754, id: 6668)
Top 2: (distance: 14.311891555786133, id: 1847)

Search result for 2th vector: 
Top 0: (distance: 0.0, id: 2)
Top 1: (distance: 14.446535110473633, id: 7354)
Top 2: (distance: 15.232194900512695, id: 2280)
```

why ?

**Comment by gobigrassland** [comment]
The reason is that version of milvus-java sdk is 2.1.0-beta, while milvus standalone is 2.0.4
