### ISSUE TITLE
IllegalAccessError: class io.milvus.grpc.CheckHealthRequest tried to access private field com.google.protobuf.AbstractMessage.memoizedSize

### ISSUE THREAD

**Issue by OceanicBreeze** [milvus-io/milvus-sdk-java#558]
<dependency>
            <groupId>io.milvus</groupId>
            <artifactId>milvus-sdk-java</artifactId>
            <version>2.2.8</version>
</dependency>

<dependency>
      <groupId>org.apache.hive</groupId>
      <artifactId>hive-exec</artifactId>
      <version>1.2.2</version>
</dependency>

java.lang.IllegalAccessError: class io.milvus.grpc.CheckHealthRequest tried to access private field com.google.protobuf.AbstractMessage.memoizedSize (io.milvus.grpc.CheckHealthRequest and com.google.protobuf.AbstractMessage are in unnamed module of loader 'app')
	at io.milvus.grpc.CheckHealthRequest.getSerializedSize(CheckHealthRequest.java:65)
	at io.grpc.protobuf.lite.ProtoInputStream.available(ProtoInputStream.java:108)
	at io.grpc.internal.MessageFramer.getKnownLength(MessageFramer.java:205)
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:137)
	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65)
	at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)
	at io.grpc.internal.DelayedStream$6.run(DelayedStream.java:283)
	at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:182)
	at io.grpc.internal.DelayedStream.access$100(DelayedStream.java:44)
	at io.grpc.internal.DelayedStream$4.run(DelayedStream.java:148)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.runQuietly(ClientCalls.java:771)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:754)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:157)
	at io.milvus.grpc.MilvusServiceGrpc$MilvusServiceBlockingStub.checkHealth(MilvusServiceGrpc.java:4523)
	at io.milvus.client.AbstractMilvusGrpcClient.checkHealth(AbstractMilvusGrpcClient.java:2727)

**Comment by yhmo** [comment]
https://stackoverflow.com/questions/64224830/illegalaccesserror-tried-to-access-field-com-google-protobuf-abstractmessage-me

**Comment by yhmo** [comment]
Answered. The IllegalAccessError is a protobuf version conflict; see https://stackoverflow.com/questions/64224830/. Closing.
