### ISSUE TITLE
Milvus client create fail: Provider io.grpc.xds.WeightedRoundRobinLoadBalancerProvider could not be instantiated

### ISSUE THREAD

**Issue by hundanLi** [milvus-io/milvus-sdk-java#566]
Exception in thread "main" java.util.ServiceConfigurationError: io.grpc.LoadBalancerProvider: Provider io.grpc.xds.WeightedRoundRobinLoadBalancerProvider could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67)
	at io.grpc.LoadBalancerRegistry.getDefaultRegistry(LoadBalancerRegistry.java:102)
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory.<init>(AutoConfiguredLoadBalancerFactory.java:53)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:635)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
	at io.milvus.client.MilvusServiceClient.<init>(MilvusServiceClient.java:52)
	at com.tcl.ai.gpt.milvus.MilvusVectorServiceImpl.init(MilvusVectorServiceImpl.java:38)
	at com.tcl.ai.gpt.milvus.MilvusVectorServiceImpl.main(MilvusVectorServiceImpl.java:27)
Caused by: java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 11 more

**Comment by hundanLi** [comment]
Version 2.2.5

**Comment by yhmo** [comment]
I have no idea. Might related to the local Java environment.

**Comment by yhmo** [comment]
Answered. Likely a local Java environment issue (xds load balancer provider could not be instantiated); no repro info. Closing.
