### ISSUE TITLE
java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocator.<init>(ZIIIIIIZ)V

### ISSUE THREAD

**Issue by caoping6** [milvus-io/milvus-sdk-java#618]
严重: [Channel<1>: (10.7.128.188:19530)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocator.<init>(ZIIIIIIZ)V
	at io.grpc.netty.Utils.createByteBufAllocator(Utils.java:176)
	at io.grpc.netty.Utils.access$000(Utils.java:75)
	at io.grpc.netty.Utils$ByteBufAllocatorPreferDirectHolder.<clinit>(Utils.java:97)
	at io.grpc.netty.Utils.getByteBufAllocator(Utils.java:144)
	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:233)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:259)
	at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:66)
	at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:201)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1878)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

19:52:57.499 [main] ERROR io.milvus.client.AbstractMilvusGrpcClient - GetIndexStateRequest RPC failed!
io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at io.milvus.grpc.MilvusServiceGrpc$MilvusServiceBlockingStub.getIndexState(MilvusServiceGrpc.java:4571)
	at io.milvus.client.AbstractMilvusGrpcClient.getIndexState(AbstractMilvusGrpcClient.java:1417)
	at com.weibo.cloud.api.service.milvus.CollectionService.getIndexes(CollectionService.java:151)
	at com.weibo.cloud.api.service.CollectionServiceTest.testGetIndexes(CollectionServiceTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocator.<init>(ZIIIIIIZ)V
	at io.grpc.netty.Utils.createByteBufAllocator(Utils.java:176)
	at io.grpc.netty.Utils.access$000(Utils.java:75)
	at io.grpc.netty.Utils$ByteBufAllocatorPreferDirectHolder.<clinit>(Utils.java:97)
	at io.grpc.netty.Utils.getByteBufAllocator(Utils.java:144)
	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:233)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:259)
	at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:66)
	at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:201)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1878)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by caopengan** [comment]
client:v2.2.12,Milvus：v2.2.11，Have you solved the same problem?

**Comment by caoping6** [comment]
I had Rolled back to the old version v2.2.5

**Comment by caopengan** [comment]
I have tested that the highest version of v2.2.13 does not report errors

**Comment by yhmo** [comment]
Not able to reproduce it. Do you have reproduce steps?

**Comment by yhmo** [comment]
@caoping6 
I see. This exception was thrown during interaction with Zilliz cloud instance, right?

**Comment by caoping6** [comment]
It was because of jar package conflict, which has been resolved.

**Comment by yanliang567** [comment]
> It was because of jar package conflict, which has been resolved.

@caoping6 could you please share how to resolve the conflict issue here?

**Comment by zihao2981** [comment]
请问你是怎么解决这个问题的， @caoping6

**Comment by caoping6** [comment]
> 请问你是怎么解决这个问题的， @caoping6
netty的依赖冲突

**Comment by xiaofan-luan** [comment]
一般来讲，需要先用mvn dependency tree找到是哪个依赖冲突
然后shade依赖

**Comment by zihao2981** [comment]
> netty

可以看下你解决的相关代码吗？ @caoping6

**Comment by egan-mw** [comment]
我也有同样的问题,但是没有依赖冲突,请问怎么解决的
<img width="1001" alt="image" src="https://github.com/milvus-io/milvus-sdk-java/assets/48442717/ae3f84c3-d09d-4f83-8566-a3c903a942ac">
<img width="1123" alt="image" src="https://github.com/milvus-io/milvus-sdk-java/assets/48442717/cc422b70-f168-405f-8d6d-d058b52a8ab7">

**Comment by egan-mw** [comment]
@xiaofan-luan

**Comment by xiaofan-luan** [comment]
@egan-mw try 2.3.5 see if it solved your probleam

**Comment by egan-mw** [comment]
> @egan-mw try 2.3.5 see if it solved your probleam

sdk使用2.3.5解决了问题,谢谢!
