### ISSUE TITLE
[BUG] Search failed with exception if no search result 

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/milvus-sdk-java#64]
`test_search_range_no_result (io.milvus.client.MilvusGrpcClient@7b4619a3, IP_GpPOyWPTUN)
java.lang.ArithmeticException: / by zero
	at io.milvus.client.MilvusGrpcClient.buildSearchResponse(MilvusGrpcClient.java:744)
	at io.milvus.client.MilvusGrpcClient.search(MilvusGrpcClient.java:349)
	at com.TestSearchVectors.test_search_range_no_result(TestSearchVectors.java:430)
	at com.MainClass.main(MainClass.java:142)
... Removed 22 stack frames
`
SDK_version: 0.3.1RC-SNAPSHOT

**Comment by youny626** [comment]
Done
