### ISSUE TITLE
Loading collection console log keeps looping with errors in milvus-sdk-java 2.4.0

### ISSUE THREAD

**Issue by CSi-CJ** [milvus-io/milvus-sdk-java#880]
## Problem Description
When calling the `loadCollection` method after creating a collection with `milvus-sdk-java` 2.4.0, the `MilvusServiceClient` keeps executing a loading loop and throwing errors. Weirdly, `milvus-attu` shows that the collection has been loaded, but the console log keeps looping with errors.
![image](https://github.com/milvus-io/milvus-sdk-java/assets/57539387/c6527a42-a90b-459b-908f-6eaff63d186f)
![image](https://github.com/milvus-io/milvus-sdk-java/assets/57539387/9bebd675-0316-462d-ab3f-e60157f3508c)

## Error Log
```
2024-04-26T15:31:33.347+08:00 RID-b04b984f-fb0f-44d6-9ca7-780db24edb53  WARN 34720 --- [nio-8443-exec-1] i.m.client.AbstractMilvusGrpcClient      : Retry(6) with interval 2430ms. Reason: CANCELLED: Failed to read message.
2024-04-26T15:31:35.806+08:00 RID-b04b984f-fb0f-44d6-9ca7-780db24edb53 ERROR 34720 --- [nio-8443-exec-1] i.m.client.AbstractMilvusGrpcClient      : LoadCollectionRequest collectionName:Entity_100000001_Multi_Vector_3cf4e5916b0549b7ab79d6c0b71be4ce RPC failed! Exception:{}

io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:275) ~[grpc-stub-1.57.2.jar:1.57.2]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:256) ~[grpc-stub-1.57.2.jar:1.57.2]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:169) ~[grpc-stub-1.57.2.jar:1.57.2]
	at io.milvus.grpc.MilvusServiceGrpc$MilvusServiceBlockingStub.showCollections(MilvusServiceGrpc.java:4073) ~[milvus-sdk-java-2.4.0.jar:na]
	at io.milvus.client.AbstractMilvusGrpcClient.waitForLoadingCollection(AbstractMilvusGrpcClient.java:94) ~[milvus-sdk-java-2.4.0.jar:na]
	at io.milvus.client.AbstractMilvusGrpcClient.loadCollection(AbstractMilvusGrpcClient.java:565) ~[milvus-sdk-java-2.4.0.jar:na]
	at io.milvus.client.MilvusServiceClient.lambda$loadCollection$8(MilvusServiceClient.java:454) ~[milvus-sdk-java-2.4.0.jar:na]
	at io.milvus.client.MilvusServiceClient.retry(MilvusServiceClient.java:290) ~[milvus-sdk-java-2.4.0.jar:na]
	at io.milvus.client.MilvusServiceClient.loadCollection(MilvusServiceClient.java:454) ~[milvus-sdk-java-2.4.0.jar:na]
	at com.ot.ais.service.search.data.impl.MilvusDatabaseServiceImpl.loadCollection(MilvusDatabaseServiceImpl.java:250) ~[classes/:na]
	at com.ot.ais.service.search.data.impl.MilvusDatabaseServiceImpl.createIndexesAndLoadCollection(MilvusDatabaseServiceImpl.java:151) ~[classes/:na]
	at com.ot.ais.service.search.data.impl.MilvusDatabaseServiceImpl.createCollection(MilvusDatabaseServiceImpl.java:131) ~[classes/:na]
```

## Environment
- milvus-sdk-java version: 2.4.0
- JDK version:  17
- Operating System: windows

## Steps to Reproduce
1. define method loadCollection:
```@Override
    public R<RpcStatus> loadCollection(String collectionName) {
        return milvusServiceClient.loadCollection(
          LoadCollectionParam.newBuilder()
            .withCollectionName(collectionName)
            .build()
        );
    }
```
2. invoke loadCollection()

## Expected Behavior
The collection should be loaded successfully without looping errors.

## Additional Information
Hope someone can help me resolve this issue.

Additionally, I noticed that the `MilvusServiceClient` has a default retry mechanism for almost every database interaction with `private int maxRetryTimes = 75`. Why is the retry count set to 75? Is there any specific reason behind this number?

![image](https://github.com/milvus-io/milvus-sdk-java/assets/57539387/bfbf6fdc-104a-4ba6-8de3-20b8ab9940de)

**Comment by yhmo** [comment]
The retry machinery is consistent with the milvus python sdk: https://github.com/milvus-io/pymilvus/blob/1081c49fcc21039300fec22e7b19805be8f198f0/pymilvus/decorators.py#L42

The loadCollection() calls showCollection() to check loading progress. Seems the showCollection() failed in rpc.

**Comment by CSi-CJ** [comment]
Yeah, it seems like grpc connection has crashed. I launched the Milvus standalone cluster in the local Ubuntu environment, the infra is as below:
![image](https://github.com/milvus-io/milvus-sdk-java/assets/57539387/dc0f420c-e6e7-4790-a0c6-7a17f7917bbf)
I almost found the root cause where is,  cause my Milvus helm chart installs failed, and the query-node pod has not been found.  I think maybe reinstalling the Milvus cluster can work normally

**Comment by CSi-CJ** [comment]
Yeah, it seems like grpc connection has crashed. I launched the Milvus standalone cluster in the local Ubuntu environment, the infra is as below:
I almost found the problem where is, cause my Milvus helm chart installs failed, and the query-node pod has not been found. I think maybe reinstalling the Milvus cluster can work normally. please help me confirm whether the cluster status is correct
![image](https://github.com/milvus-io/milvus-sdk-java/assets/57539387/48652405-2aa8-406e-9c48-51619b3db07a)

**Comment by yhmo** [comment]
The querycoord failed to initialize. Need the full log to know what the error is.

**Comment by yhmo** [comment]
Answered. The looping load error was traced to a querycoord initialization failure in the user's deployment, not the SDK. Closing.
